### ISSUE TITLE
Question regarding evaluation metrics

### ISSUE THREAD

**Issue by LXXXXR** [hellowangqian/multi-label-image-classification#4]
https://github.com/hellowangqian/multi-label-image-classification/blob/1d9ef29d798f71e3b8d4c84c026017b6c1ce2695/VOC2007/evaluation_metrics.py#L39
Thank you for the work! 
Just a minor concern: for VOC dataset, why does the prf_cal function require y_true only contains {0, 1} rather than {-1, 0, 1}?
And this function seems to only provide the average overall performance, so I was wondering where I can find codes for average per-label results.

**Comment by hellowangqian** [comment]
The code also applies to the case of {-1, 0, 1} since it only considers the positive labels (i.e. ones). For per-image or per-label results, you need to modify the code to calculate the TP/GT for each row or each column.

**Comment by LXXXXR** [comment]
Cool! That really helps.

**Comment by LXXXXR** [comment]
Cool! That really helps.
